name: 'Infra - Dev'
on:
  push:
    branches:
    - dev
    path:
    - 'terraform/*'
    - '.github/workflows/ci-dev.yml'

  pull_request:
    branches:
    - dev
    path:
    - 'terraform/*'
    - '.github/workflows/ci-dev.yml'

jobs:
  terraform:
    name: "Dev deploy"
    uses: "./.github/workflows/terraform-deploy.yaml"
    with:
      env: dev
    secrets: inherit
