name: 'Infra - Dev'
on:
  push:
    branches:
    - dev
    path:
    - 'terraform/*'
    - '.github/workflows/ci-dev.yml'

  pull_request:
    branches:
    - dev
    path:
    - 'terraform/*'
    - '.github/workflows/ci-dev.yml'


permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    environment: dev
    steps:
      - name: Deploy
        uses: "./.github/template/deploy" 
