name: 'Infra - Dev'
on:
  push:
    branches:
    - dev
    path:
    - 'terraform/*'
    - '.github/workflows/ci-dev.yml'

  pull_request:
    branches:
    - dev
    path:
    - 'terraform/*'
    - '.github/workflows/ci-dev.yml'

#
# permissions:
#   contents: read
#   pull-requests: write

jobs:
  terraform:
    uses: "./.github/workflows/terraform_deploy.yaml"
    with:
      env: dev
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
