name: 'Infra - Dev'
on:
  push:
    branches:
    - dev
    path:
    - 'terraform/*'
    - '.github/workflows/ci-dev.yml'

  pull_request:
    branches:
    - dev
    path:
    - 'terraform/*'
    - '.github/workflows/ci-dev.yml'

jobs:
  terraform:
    if: "(github.event_name == 'push' && !contains(github.event.head_commit.message, 'Merge pull request')) || (github.event_name == 'pull_request')"
    name: "Dev deploy"
    uses: "./.github/workflows/terraform-deploy.yaml"
    with:
      env: dev
    secrets: inherit
