name: 'Infra - Stage'

on:
  push:
    branches:
    - main
    path:
    - 'terraform/*'
    - '.github/workflows/ci-dev.yml'

  pull_request:
    branches:
    - main
    path:
    - 'terraform/*'
    - '.github/workflows/ci-dev.yml'

jobs:
  terraform:
    name: "Stage deploy"
    uses: "./.github/workflows/terraform-deploy.yaml"
    with:
      env: stage
    secrets: inherit
