name: Deploy to production

on:
  workflow_dispatch:
    inputs:
      name:

jobs:
  terraform:
    name: "Prod deploy"
    uses: "./.github/workflows/terraform_deploy.yaml"
    with:
      env: prod
    secrets: inherit
